[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 2000

[rpc_endpoints]
arc = "https://rpc.mainnet.arc.io"
